---
- name: Kubelet | reload systemd
  systemd_service:
    daemon_reload: true
  listen: Node | restart kubelet

- name: Kubelet | restart kubelet
  include_tasks: tasks/restart-kubelet.yml
  listen: Node | restart kubelet
