---
- name: Kubeadm | reload systemd
  systemd_service:
    daemon_reload: true
  listen: Kubeadm | restart kubelet

- name: Kubeadm | reload kubelet
  include_tasks: ../../node/tasks/restart-kubelet.yml
  listen: Kubeadm | restart kubelet
